### ISSUE TITLE
Scaffold script aborts when encountering an empty repository

### ISSUE THREAD

**Issue by jeffcshapiro** [lfscanning/scaffold#49]
Scaffold Python script will error out when it hits a GitHub repo that is empty.  This is deterministic and repeatable.  Example repo and stack trace below:

https://github.com/com-pas/compas-ui

lfenergy/compas: cloning git@github.com:com-pas/compas-ui.git
Traceback (most recent call last):
  File "/home/ubuntu/scaffold-code/scaffold/scaffold.py", line 293, in <module>
    ran_command = exec_command(SCAFFOLD_HOME, cfg, sys.argv)
  File "/home/ubuntu/scaffold-code/scaffold/scaffold.py", line 167, in exec_command
    doNextThing(SCAFFOLD_HOME, cfg, fdServer, prj_only, sp_only)
  File "/home/ubuntu/scaffold-code/scaffold/runners.py", line 31, in doNextThing
    retval = doNextThingForProject(scaffold_home, cfg, fdServer, prj, sp_only)
  File "/home/ubuntu/scaffold-code/scaffold/runners.py", line 50, in doNextThingForProject
    retval = doNextThingForSubproject(scaffold_home, cfg, fdServer, prj, sp)
  File "/home/ubuntu/scaffold-code/scaffold/runners.py", line 143, in doNextThingForSubproject
    return doGetRepoCodeForSubproject(cfg, prj, sp)
  File "/home/ubuntu/scaffold-code/scaffold/getcode.py", line 47, in doGetRepoCodeForSubproject
    cmts = list(r.iter_commits())
  File "/home/ubuntu/scaffold-code/venv/lib/python3.8/site-packages/git/repo/base.py", line 582, in iter_commits
    rev = self.head.commit
  File "/home/ubuntu/scaffold-code/venv/lib/python3.8/site-packages/git/refs/symbolic.py", line 217, in _get_commit
    obj = self._get_object()
  File "/home/ubuntu/scaffold-code/venv/lib/python3.8/site-packages/git/refs/symbolic.py", line 210, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/ubuntu/scaffold-code/venv/lib/python3.8/site-packages/git/refs/symbolic.py", line 151, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/home/ubuntu/scaffold-code/venv/lib/python3.8/site-packages/git/refs/symbolic.py", line 201, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/home/ubuntu/scaffold-code/venv/lib/python3.8/site-packages/git/refs/symbolic.py", line 184, in _get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/heads/master' does not exist

**Comment by goneall** [comment]
Two possible solutions:
- If a repo is empty, don't add to the repos list
- Handle an empty repo by ignoring it when downloading - print a status "repo empty, ignoring"

Second - preferred
